parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
rules:
  indent:
    - 2
    - 2
    - SwitchCase: 1
  quotes:
    - 2
    - single
  semi:
    - 2
    - always
  no-var: 2
env:
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
