language: node_js
node_js:
  - "node"
  - "4"

branches:
  only:
    - master
    - /^greenkeeper\/.*$/

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - if [ "$TRAVIS_NODE_VERSION" = "4" ]; then
      npm install -g npm@5;
      npm --version;
    fi

script:
  - npm run cover

after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
