language: node_js
node_js:
  - "node"
  - "6"

branches:
  only:
    - master
    - /^greenkeeper\/.*$/

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - if [ "$TRAVIS_NODE_VERSION" = "6" ]; then
      npm install -g npm@6;
      npm --version;
    fi

script:
  - npm run cover

after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
