language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "iojs"

cache:
  directories:
    - node_modules

script:
  - npm run cover

after_script:
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
